version: "3.8"

services:
  web:
    image: php:8.1-apache
    container_name: grenier_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    working_dir: /var/www/html
    networks:
      - grenier_net
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"

  node:
    image: node:18
    container_name: grenier_node
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run watch"
    networks:
      - grenier_net

  db:
    image: mysql:5.7
    container_name: grenier_db
    restart: always
    environment:
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - grenier_net

volumes:
  db_data:

networks:
  grenier_net:
